image: alpine:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apk add --update zola
    - zola build

deploy:
  stage: deploy
  script:
    - mkdir public
    - cp -r public/* ./public
  only:
    - main  # Определите ветку, на которой должно выполняться развертывание, например, 'main'
  artifacts:
    paths:
      - public/
